### ISSUE TITLE
Read timeout error stops all processes

### ISSUE THREAD

**Issue by G4m3M4ni4c** [LukeMurphey/splunk-website-monitoring#8]
The app stops checking web availability after this error occurs:

`2016-09-01 05:02:09,161 ERROR Execution failed
Traceback (most recent call last):
  File "F:\Program Files\Splunk\etc\apps\website_monitoring\bin\modular_input.py", line 1277, in execute
    self.do_run(in_stream, log_exception_and_continue=True)
  File "F:\Program Files\Splunk\etc\apps\website_monitoring\bin\modular_input.py", line 1177, in do_run
    input_config)
  File "F:\Program Files\Splunk\etc\apps\website_monitoring\bin\web_ping.py", line 491, in run
    result = WebPing.ping(url, username, password, timeout, proxy_type, proxy_server, proxy_port, proxy_user, proxy_password, client_certificate, client_certificate_key, user_agent, logger=self.logger)
  File "F:\Program Files\Splunk\etc\apps\website_monitoring\bin\web_ping.py", line 301, in ping
    auth_type = cls.determine_auth_type(url, proxies=proxies, timeout=timeout, cert=cert, logger=logger)
  File "F:\Program Files\Splunk\etc\apps\website_monitoring\bin\web_ping.py", line 149, in determine_auth_type
    http = requests.get(url.geturl(), proxies=proxies, timeout=timeout, cert=cert, verify=False)
  File "F:\Program Files\Splunk\etc\apps\website_monitoring\bin\website_monitoring_app\requests\api.py", line 65, in get
    return request('get', url, **kwargs)
  File "F:\Program Files\Splunk\etc\apps\website_monitoring\bin\website_monitoring_app\requests\api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "F:\Program Files\Splunk\etc\apps\website_monitoring\bin\website_monitoring_app\requests\sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\Program Files\Splunk\etc\apps\website_monitoring\bin\website_monitoring_app\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "F:\Program Files\Splunk\etc\apps\website_monitoring\bin\website_monitoring_app\requests\adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)`

**Comment by LukeMurphey** [comment]
I see the problem. Fixing it now.

**Comment by LukeMurphey** [comment]
Fixed in 1.6.1.
